### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xperl6#30]
In order to launch we should:

- [ ] Turn on Travis CI for the track
- [ ] Add Perl 6 as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [ ] Implement at least 10 problems
- [ ] Write documentation (see below)
- [ ] Find a person or (ideally) a handful of people willing to check exercism regularly (daily?) to review solutions
- [ ] Add track implementors and other designated code reviewers as mentors to the track. This gives you access to all the solutions in Perl 6 whether or not you've submitted the problem to the site.
- [ ] Add a language icon or logo (see below)
- [ ] Toggle `"active"` to `true` in `config.json`
- [ ] Mention it in the next "Behind the Scenes" newsletter (kytrinyx)

## Documentation

The documentation lives in the `docs/` directory here in this repository, and gets served to the site via the x-api. It should contain at minimim:

- `INSTALLATION.md` - about how to get the language set up locally.
- `TESTS.md` - about how to run the tests for the exercises.

Some nice to haves:

- `ABOUT.md` - a short, friendly blurb about the language. What types of problems does it solve really well? What is it typically used for?
- `LEARNING.md` - a few notes about where people might want to go to learn the language from scratch.
- `RESOURCES.md` - references and other useful resources.

## Logo/Icon

We try to create a language icon that has the exercism colors, and is recognizably similar to the language icon. Sometimes this isn't possible due to copyright issues. See http://exercism.io/languages for all the existing icons.

The logo should live under `/public/img/tracks/` in the exercism/exercism.io repository.
https://github.com/exercism/exercism.io/tree/master/public/img/tracks

Attribution goes in https://github.com/exercism/exercism.io/blob/master/ATTRIBUTION.md

If image assets are not your strong suit, just find a reasonable image to start from, along with the information about the licensing, and we'll figure out the colorization thing (I've written some scripts to help me do this part).

Some icons are the official language logo (tweaked). Where a language doesn't seem to have an official logo, or where the official logo has copyright issues, we just make something up.

## Successful Launches

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The code reviews do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore aspects of the language. Referencing existing blog posts and style guides seems to work well, when making specific recommendations.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by mienaikage** [comment]
`test_pattern` included in https://github.com/exercism/xperl6/pull/42

**Comment by mienaikage** [comment]
@kytrinyx Could you add me to the perl 6 track mentors on the site?

**Comment by kytrinyx** [comment]
Done!

**Comment by mienaikage** [comment]
I think the track is in a good state for becoming active at this point. Hopefully when it does it'll attract a few more contributors to the repository 🙂

**Comment by mienaikage** [comment]
Created PR https://github.com/exercism/xperl6/pull/158 for toggling `active` to `true`

**Comment by kytrinyx** [comment]
@mienaikage Do you go to any Perl 6 meetups or hang out in any Perl 6 forums or chatrooms? If so, would you see if you can entice anyone else to come help keep an eye on things here (review PRs, discuss issues) and/or on the website (give people feedback)? If we could get 2 or 3 people involved, that would ensure that people can have vacations and babies and mid-life crises without the track suffering from it.

**Comment by mienaikage** [comment]
There is the [#perl6 IRC channel](http://webchat.freenode.net/?channels=perl6&nick=), I'll let people on there know that the track is going live and see if I can tempt a few people to jump on.

There's also a Perl social in London coming up on 8th June so I may go along to that.

**Comment by kytrinyx** [comment]
Both of those sound great!

**Comment by kotp** [comment]
Not to mention the [Gitter Room on Exercism for perl!](https://gitter.im/exercism/xperl), but I want to...

**Comment by mienaikage** [comment]
Posted on the IRC and the Perl 6 Facebook group. The site also got a mention in the [Perl 6 weekly](https://p6weekly.wordpress.com/2017/05/22/2017-21-yap6b/) blog 🙂

**Comment by kytrinyx** [comment]
> The site also got a mention in the Perl 6 weekly  blog

Very cool!
